listen_addresses = ['127.0.0.1:53']
force_tcp = true
timeout = 5000
keepalive = 30
cert_refresh_delay = 240
bootstrap_resolvers = ['217.218.155.155:53', '217.218.127.127:53']
ignore_system_dns = true
cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[static]
  [static.bitcoinvps-cloud]
    stamp = 'sdns://AQMAAAAAAAAAFDU0LjE4My4yMDEuMTUyOjE1MzUzIInRnqCMiIR__6W_n8QvNAdO5YuWf5yv4rprMKbgbb8IJDIuZG5zY3J5cHQtY2VydC5kbnMuYml0Y29pbnZwcy5jbG91ZA'
[blocked_names]
# blocked_names_file = 'porn.txt'
[allowed_names]
# allowed_names_file = 'whitelist.txt'
